name: 'public_docker_image_test'
on:
  workflow_dispatch

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    container: hello-world
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: ls
        run: ls
      
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Run container
        run: |
          docker run hello-world
